// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        input: string;
        label: string;
        "mui-auto-fill-cancel": string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
